nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['http://localhost:*', 'http://devsfecations.fr', 'https://devsfecations.fr']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Content-Name']
        max_age: 3600
    paths:
        '^/': null
